name: Rollback

on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Rollback info
        run: |
          echo "Rollback workflow executed" > rollback_logs.txt
          echo "User: ${{ github.actor }}" >> rollback_logs.txt
          echo "Date: $(date)" >> rollback_logs.txt

      - name: Upload rollback logs
        uses: actions/upload-artifact@v4
        with:
          name: rollback-logs
          path: rollback_logs.txt
